sudo: required
services: 
- docker

script:
- docker build -t mhooimeijer/node .
- docker images mhooimeijer/node

before_deploy:
- docker login -u mhooimeijer -p '$8JLD7fNj!qP4mxM'

docvker
deploy:
  provider: script
  script: docker push mhooimeijer/node
  on:
    branch: master